### ISSUE TITLE
Form Fails to Render With Checkboxes

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/content-types#86]
On form render, the following error is thrown:

```
Template render error: (unknown path)
 Error: Cannot use "in" operator to search for "1" in unexpected types.
   at Object.exports.prettifyError (/Users/project/node_modules/nunjucks/src/lib.js:34:15)
   at /Users/project/node_modules/nunjucks/src/environment.js:485:31
   at root [as rootRenderFunc] (eval at <anonymous> (/Users/project/node_modules/nunjucks/src/environment.js:564:24), <anonymous>:137:3)
   at Obj.extend.render (/Users/project/node_modules/nunjucks/src/environment.js:478:15)
   at Obj.extend.renderString (/Users/project/node_modules/nunjucks/src/environment.js:326:21)
   at Object.module.exports.renderString (/Users/project/node_modules/nunjucks/index.js:80:14)
   at type.attributes.map.input (/Users/project/node_modules/punchcard-content-types/lib/form/html.js:153:27)
   at Array.map (native)
   at Promise (/Users/project/node_modules/punchcard-content-types/lib/form/html.js:146:36)
   at renderer (/Users/project/node_modules/punchcard-content-types/lib/form/html.js:145:10)
   at Function.form (/Users/project/node_modules/punchcard-content-types/lib/form.js:11:10)
   at content.only.then.merged (/Users/project/node_modules/punchcard-cms/lib/routes/content.js:111:24)
```

It appears to be affecting content types that use input plugins with type `checkbox`, and may also affect input plugins using type `select` or `radio` as well. Likely related to the `required` attribute.

## Steps for Reproducing

- Start local Punchcard env with latest Punchcard
- Create Content Type that includes a required checkbox
- Attempt to add a new piece of that content
- Note the Internal Server Error

## Runtime Version

v5.11

## Code Version

v4.1.0

**Comment by Snugug** [comment]
Caused by multiple items. Enumerating them here:
* https://github.com/punchcard-cms/input-plugin-boolean/pull/62
* https://github.com/punchcard-cms/content-types/pull/88

**Comment by Snugug** [comment]
Repoening in order to confirm that this is resolved before closing

**Comment by Snugug** [comment]
This error is no longer affecting the code it was generated from. Closing

**Comment by Snugug** [comment]
Not resolved for editing issues
