### ISSUE TITLE
Form Generation Fails for Old CTs

### ISSUE THREAD

**Issue by Snugug** [punchcard-cms/content-types#90]
On form render after a merge with content, the following error is thrown:

```
TypeError: Cannot read property '1' of null
    at /app/node_modules/punchcard-content-types/lib/form/html.js:202:19
    at /app/node_modules/punchcard-cms/lib/routes/content.js:319:26
    at tryCatcher (/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromises (/app/node_modules/knex/node_modules/bluebird/js/release/promise.js:685:18)
```

## Steps for Reproducing

- Start local Punchcard env with Punchcard 1.0
- Create Content Type
- Add a piece of content
- Upgrade to latest Punchcard
- Edit that piece of content
- Note the form bowing up

## Runtime Version

v5.11

## Code Version

v4.1.0

**Comment by Snugug** [comment]
Confirmed working
